#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration, displays Best School and then Hi on a new line.


Figure=0

while [ $Figure -le 10 ]
do
	if [ $Figure -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((Figure++))
done
