#!/usr/bin/env bash

Figure=1

while [ $Figure -le 20 ]
do
echo $Figure
case $Figure in
4)
echo "bad luck from China"
;;
9)
echo " bad luck from Japan"
;;
17)
echo " bad luck from Italy"
;;
esac
((Figure++))
done
