#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59


Hours=0

while [ $Hours -le 12 ]; 
do
echo -n "$Hours:"

#Displaying minutes from 1 to 59
minute=1
while [ $minute  -le 59 ]; do
printf "%02d " $minute
minute=$((minute+1))
done
echo""
Hours=$((Hours+1))
done

