#!/usr/bin/env bash
# Update package list
sudo apt-get update

# Install necessary packages
sudo apt-get install -y dnsmasq

# Configure dnsmasq
echo "address=/localhost/127.0.0.2" | sudo tee /etc/dnsmasq.d/localhost.conf
echo "server=/facebook.com/8.8.8.8" | sudo tee /etc/dnsmasq.d/facebook.conf

# Restart dnsmasq service
sudo systemctl restart dnsmasq.service
fi
